name: parecido_examen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  sqflite_common_ffi: ^2.3.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
localizations:
    arb-dir: lib/l10n
    template-arb-file: app_es.arb
    output-localization-file: app_localizations.dart